-- RE1 Expanded Question Bank (Q21–Q160)
-- Run AFTER re1_schema.sql (depends on public.re1_questions existing).
-- Brings the seed bank to 160 active questions across all 16 topic tags.
-- Distribution of the full 160-question bank (incl. the 20 in re1_schema.sql):
--   Level 1 ~24 | Level 2 ~64 | Level 3 ~44 | Level 4 ~28
-- NOTE: Legislative references reflect commonly examined FAIS positions and
--       should be confirmed by a subject-matter expert before launch.

INSERT INTO public.re1_questions (question_number, topic_tag, complexity_level, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, legislative_ref) VALUES

-- ======================= DEBARMENT (Section 14) =======================
(21, 'debarment_s14', 1, 'Which body maintains the central register on which debarred persons are recorded and published?', 'The FAIS Ombud', 'The Financial Sector Conduct Authority (FSCA)', 'The South African Revenue Service', 'The Financial Intelligence Centre', 'B', 'The FSCA maintains and publishes the central register of debarred persons so that other FSPs can verify a person''s status before appointing them.', 'FAIS Act s14(8)'),
(22, 'debarment_s14', 2, 'When an FSP debars a representative, what right must it communicate to the affected person?', 'A right to immediate re-employment elsewhere', 'A right to a severance payment', 'The right to request reasons and to apply to the Financial Services Tribunal for reconsideration', 'No rights, as debarment is final', 'C', 'A debarment is administrative action; the FSP must give reasons and inform the person of their right to apply to the Financial Services Tribunal for reconsideration.', 'FAIS Act s14; FSR Act s230'),
(23, 'debarment_s14', 2, 'What is the principal purpose of the statutory debarment mechanism in the FAIS Act?', 'To penalise FSPs for poor performance', 'To protect the public by preventing persons who are not fit and proper from rendering financial services', 'To resolve salary disputes between FSPs and staff', 'To collect outstanding levies from representatives', 'B', 'Debarment is a consumer-protection tool that removes persons who are no longer honest, of integrity, or competent from the financial services industry.', 'FAIS Act s14'),
(24, 'debarment_s14', 3, 'A representative resigns. Seven months later the FSP discovers the representative committed fraud while still employed. What is the FSP''s correct course of action regarding debarment?', 'Debar the former representative immediately under section 14', 'It is too late to debar under section 14 (the 6-month window has passed); the matter should be reported to the FSCA', 'Extend the window by mutual agreement and then debar', 'Refer the matter to the FAIS Ombud for debarment', 'B', 'An FSP may only commence debarment of a former representative within 6 months of termination; after that period it cannot debar but should report the conduct to the FSCA.', 'FAIS Act s14(5)'),
(25, 'debarment_s14', 4, 'Consider these statements about debarment: i. The FSP must keep a record of the debarment. ii. The grounds must have existed and become known while the person was a representative or within 6 months of termination. iii. A debarment may be imposed purely to penalise poor sales performance. iv. The debarred person must be informed of the debarment and its reasons. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — debarment may not be used as a performance or disciplinary penalty; it must rest on fit-and-proper or material-breach grounds.', 'FAIS Act s14'),

-- ======================= FAIS OMBUD =======================
(26, 'fais_ombud', 1, 'What is the maximum monetary amount the FAIS Ombud may award in a determination?', 'R250,000', 'R500,000', 'R800,000', 'There is no monetary limit', 'C', 'The FAIS Ombud''s monetary jurisdiction is limited to R800,000 per determination; larger claims must be pursued through the courts.', 'FAIS Act s28; Ombud Rules'),
(27, 'fais_ombud', 1, 'Before approaching the FAIS Ombud, a client must first lodge the complaint with whom?', 'The High Court', 'The FSP against which the complaint is made', 'The FSCA', 'The Prudential Authority', 'B', 'A complaint must first be lodged with the FSP so it has an opportunity to resolve the matter internally before escalation to the Ombud.', 'GCC BN80 of 2003; BN81 of 2003'),
(28, 'fais_ombud', 2, 'In carrying out its functions, the FAIS Ombud is required to act in a manner that is:', 'Formal and strictly procedural like a court', 'Independent, impartial and according to the principles of equity, informally and expeditiously', 'Aligned with the commercial interests of FSPs', 'Confidential to the point of issuing no reasons', 'B', 'The Ombud must resolve complaints independently, impartially and equitably, in an informal, economical and expeditious manner.', 'FAIS Act s20; BN81 of 2003'),
(29, 'fais_ombud', 2, 'Which of the following is generally OUTSIDE the FAIS Ombud''s jurisdiction?', 'A dispute about unsuitable advice causing financial loss', 'A failure to disclose product fees', 'A claim that, in monetary value, exceeds the Ombud''s prescribed limit', 'A failure to conduct a needs analysis', 'C', 'Claims exceeding the Ombud''s monetary jurisdiction fall outside its powers and must be pursued in the courts (unless the parties agree to abandon the excess).', 'FAIS Act s27; Ombud Rules'),
(30, 'fais_ombud', 2, 'Within how many days of receipt must an FSP, under the General Code, acknowledge a client''s written complaint?', 'A reasonable time, with proper records of all complaints maintained', 'Exactly 24 hours', 'Within 90 days only', 'No acknowledgement is required', 'A', 'The General Code requires FSPs to maintain a documented internal complaints process and to handle complaints promptly, keeping records of each complaint and its outcome.', 'GCC BN80 of 2003, s17-19'),
(31, 'fais_ombud', 3, 'A client''s complaint remains unresolved 6 weeks after being lodged with the FSP. The FSP tells the client they must first sue in the Magistrate''s Court. Is this correct?', 'Yes, court action is a precondition to the Ombud', 'No — after 6 weeks unresolved, the client may refer the complaint directly to the FAIS Ombud', 'Yes, but only for amounts over R800,000', 'No — the client must wait 6 months first', 'B', 'Once the internal process has run for 6 weeks without resolution, the client is entitled to escalate to the FAIS Ombud; court action is not a precondition.', 'BN81 of 2003'),
(32, 'fais_ombud', 4, 'Consider: i. An Ombud determination has the force of a civil court judgment. ii. A party dissatisfied with a determination may apply to the Financial Services Tribunal for reconsideration. iii. The Ombud may decline matters more appropriately dealt with by a court. iv. The Ombud''s monetary jurisdiction is unlimited. Which combination is CORRECT?', 'i, ii and iii only', 'i and iv only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iii are correct. Statement iv is wrong — the Ombud''s monetary jurisdiction is capped (R800,000).', 'FAIS Act ss20, 27, 28; FSR Act s230'),

-- ======================= KEY INDIVIDUAL DUTIES =======================
(33, 'key_individual_duties', 1, 'A Key Individual must be approved by which authority before managing or overseeing the financial services of an FSP?', 'The FAIS Ombud', 'The Financial Sector Conduct Authority (FSCA)', 'The relevant product supplier', 'The Compliance Officer', 'B', 'A person may only act as a Key Individual once approved by the FSCA, having met the fit-and-proper requirements.', 'FAIS Act s8; Board Notice 194 of 2017'),
(34, 'key_individual_duties', 2, 'What is the core statutory function of a Key Individual?', 'To personally sell as many products as possible', 'To manage and oversee the financial services rendered by the FSP (or the relevant part of it)', 'To audit the FSP''s annual financial statements', 'To set the FSP''s product pricing', 'B', 'A Key Individual is responsible for managing and overseeing the activities of the FSP relating to the rendering of financial services.', 'FAIS Act s1; Board Notice 194 of 2017'),
(35, 'key_individual_duties', 2, 'If an FSP is left without an approved Key Individual, what is the most likely regulatory consequence?', 'Nothing, as a KI is optional', 'The FSP''s ability to operate is jeopardised and its licence may lapse or be suspended if not remedied', 'The Compliance Officer automatically becomes the KI', 'The FSCA appoints a KI on the FSP''s behalf', 'B', 'A licensed FSP must have at least one approved Key Individual; an unfilled vacancy that is not remedied within a reasonable period places the licence at risk.', 'FAIS Act ss8, 11'),
(36, 'key_individual_duties', 2, 'Which statement about a Key Individual''s oversight responsibility is correct?', 'A KI may oversee subcategories for which they are not themselves approved', 'A KI may only manage and oversee financial services in the categories and subcategories for which they are approved', 'A KI has no responsibility for representatives'' conduct', 'A KI is exempt from continuous professional development', 'B', 'A KI''s management and oversight is limited to the product categories and subcategories for which they have been approved as fit and proper.', 'Board Notice 194 of 2017'),
(37, 'key_individual_duties', 3, 'A newly approved Key Individual is assigned to oversee a team of representatives selling long-term insurance, a subcategory for which the KI has no approval. What is the correct position?', 'This is acceptable as long as the KI is experienced', 'The KI may not oversee that subcategory until properly approved for it; the FSP must arrange appropriate oversight', 'The representatives can oversee themselves', 'The Compliance Officer must take over all advice', 'B', 'Oversight must be exercised by a KI approved for the relevant subcategory; the FSP cannot lawfully place reps under a KI who lacks approval for that line.', 'Board Notice 194 of 2017'),
(38, 'key_individual_duties', 3, 'An FSP applies for a licence but its proposed Key Individual cannot demonstrate the required management experience. What is the likely outcome?', 'The licence is granted with no conditions', 'The application may be refused or granted subject to the KI operating under supervision until requirements are met', 'The FSP must appoint two Compliance Officers instead', 'The FAIS Ombud must approve the KI', 'B', 'Where a KI does not yet meet experience requirements, the FSCA may refuse the application or impose supervision conditions until competence is demonstrated.', 'Board Notice 194 of 2017'),
(39, 'key_individual_duties', 4, 'Consider: i. A KI must manage and oversee the FSP''s financial services. ii. A KI must remain fit and proper on a continuous basis. iii. A KI is automatically also a representative of the FSP. iv. A KI may be responsible for ensuring representatives meet competency timelines. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — a KI is not automatically a representative; the roles are distinct, though one person may hold both.', 'FAIS Act; Board Notice 194 of 2017'),
(40, 'key_individual_duties', 4, 'Consider these statements on KI accountability: i. The KI bears responsibility for the FSP''s compliance with FAIS in the area they oversee. ii. The KI may delegate management duties but not ultimate accountability. iii. A KI need not be involved in the FSP''s day-to-day operations. iv. The KI''s approval can be withdrawn if they cease to be fit and proper. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'i, iii and iv only', 'ii, iii and iv only', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — effective management and oversight requires genuine, ongoing involvement, not a passive title.', 'FAIS Act ss8, 9; Board Notice 194 of 2017'),

-- ======================= COMPLIANCE OFFICER =======================
(41, 'compliance_officer', 1, 'When is an FSP obliged to appoint a compliance officer under the FAIS Act?', 'Only if it is a Category IV FSP', 'When it has more than one Key Individual or one or more representatives, as prescribed', 'Only when instructed by the FAIS Ombud', 'Never; compliance is voluntary', 'B', 'FSPs of a prescribed size (typically more than one KI and/or one or more representatives) must appoint a compliance officer to monitor compliance.', 'FAIS Act s17'),
(42, 'compliance_officer', 2, 'To whom does a compliance officer submit compliance reports, and how often?', 'To the FAIS Ombud, monthly', 'To the FSCA, at the intervals and in the form prescribed (typically annually)', 'To SARS, quarterly', 'To the product supplier, weekly', 'B', 'Compliance officers must submit compliance reports to the FSCA at prescribed intervals, generally annually, in the prescribed format.', 'FAIS Act s17; Board Notice 194 of 2017'),
(43, 'compliance_officer', 2, 'What is the primary role of an FSP''s compliance officer?', 'To generate sales leads', 'To monitor compliance with the FAIS Act and report to management and the FSCA', 'To approve client claims', 'To set commission rates', 'B', 'The compliance officer monitors the FSP''s compliance with FAIS and reports findings to management and the regulator.', 'FAIS Act s17'),
(44, 'compliance_officer', 2, 'Which requirement must a person meet to be approved as a compliance officer?', 'Be a qualified actuary', 'Meet the prescribed competence, experience and integrity requirements and be approved by the FSCA', 'Hold the RE5 examination only', 'Be a director of a product supplier', 'B', 'Compliance officers must satisfy prescribed competence, experience and honesty/integrity requirements and obtain FSCA approval.', 'FAIS Act s17; Board Notice 194 of 2017'),
(45, 'compliance_officer', 3, 'A sole proprietor FSP with no employees and a single KI questions whether it must appoint an external compliance officer. What is the correct position?', 'It must always appoint an external compliance officer', 'A small FSP that does not meet the prescribed thresholds may monitor its own compliance rather than appoint an approved compliance officer', 'It must appoint the FAIS Ombud as compliance officer', 'It is exempt from all compliance obligations', 'B', 'Smaller FSPs falling below the prescribed thresholds need not appoint a separate compliance officer but remain responsible for monitoring their own compliance.', 'FAIS Act s17'),
(46, 'compliance_officer', 3, 'An FSP appoints its top-performing salesperson as compliance officer while they continue to sell products. What concern does this raise?', 'None; multi-tasking improves efficiency', 'A conflict of interest and lack of independence, undermining objective compliance monitoring', 'The salesperson will earn too little', 'It breaches the Medical Schemes Act', 'B', 'A compliance officer must be able to monitor compliance objectively; combining the role with a sales target creates a conflict of interest that compromises independence.', 'FAIS Act s17; GCC s3A'),
(47, 'compliance_officer', 3, 'During a routine review the compliance officer finds repeated failures to keep records of advice. What is the most appropriate action?', 'Ignore it, as records are optional', 'Report the deficiency to management, recommend remedial action, and reflect it in the compliance report to the FSCA', 'Immediately debar all representatives', 'Cancel the FSP''s licence personally', 'B', 'The compliance officer''s function is to identify non-compliance, drive remediation through management, and disclose material issues in the report to the FSCA.', 'FAIS Act s17; GCC s9'),
(48, 'compliance_officer', 2, 'A compliance officer''s monitoring activities should primarily be:', 'Reactive, only after a complaint is received', 'Risk-based and ongoing, with a structured monitoring plan', 'Limited to the annual audit only', 'Delegated entirely to the external auditor', 'B', 'Effective compliance monitoring is proactive, risk-based and continuous, supported by a documented monitoring plan rather than reactive once-off checks.', 'FAIS Act s17; Board Notice 194 of 2017'),
(49, 'compliance_officer', 4, 'Consider: i. A compliance officer must be approved by the FSCA. ii. The compliance officer reports compliance findings to the FSCA. iii. Appointing a compliance officer relieves the KI of all responsibility for compliance. iv. The compliance function should be independent. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — the KI retains accountability for compliance even where a compliance officer is appointed.', 'FAIS Act ss8, 17'),

-- ======================= GENERAL CODE OF CONDUCT =======================
(50, 'general_code_of_conduct', 1, 'The General Code of Conduct for Authorised FSPs and Representatives is contained in which instrument?', 'Board Notice 194 of 2017', 'Board Notice 80 of 2003', 'FICA Act 38 of 2001', 'Government Notice 362 of 2018', 'B', 'The General Code of Conduct is set out in Board Notice 80 of 2003, issued under the FAIS Act.', 'GCC BN80 of 2003'),
(51, 'general_code_of_conduct', 2, 'What overarching duty does the General Code impose on a provider when rendering financial services?', 'To maximise commission on every transaction', 'To act honestly and fairly, with due skill, care and diligence, in the interests of clients and the integrity of the industry', 'To favour the product supplier offering the highest incentive', 'To avoid keeping any records', 'B', 'The General Code requires providers to render services honestly, fairly and with due skill, care and diligence, in the interests of clients and the integrity of the financial services industry.', 'GCC BN80 of 2003, s2'),
(52, 'general_code_of_conduct', 2, 'Under the General Code, a provider who renders advice must maintain which of the following?', 'No documentation at all', 'A record of advice reflecting the basis on which the advice was given', 'Only a copy of the client''s ID', 'A record kept solely by the product supplier', 'B', 'The Code requires a record of advice that captures the client''s needs, the products considered and the basis for the recommendation.', 'GCC BN80 of 2003, s9'),
(53, 'general_code_of_conduct', 2, 'What does the General Code require of advertising by an FSP?', 'It may exaggerate benefits to attract clients', 'It must not be misleading and must be factually correct', 'It is exempt from the Code', 'It need not identify the FSP', 'B', 'Advertisements must be factually correct, not misleading, and must comply with the specific advertising requirements of the Code.', 'GCC BN80 of 2003, s14'),
(54, 'general_code_of_conduct', 3, 'An advisor recommends replacing a client''s existing policy with a new one. What does the General Code specifically require?', 'Nothing additional; a replacement is treated like any new sale', 'Full disclosure of the actual and potential implications, costs and consequences of the replacement to the client', 'That the client waive all rights to advice', 'That the old insurer approve the replacement', 'B', 'Where a transaction involves replacing an existing product, the provider must disclose the implications, costs and risks of the replacement so the client can make an informed decision.', 'GCC BN80 of 2003, s8'),
(55, 'general_code_of_conduct', 3, 'A provider receives and holds client premiums before paying them to the product supplier. What does the General Code require regarding these funds?', 'They may be used for the FSP''s working capital', 'They must be handled in accordance with the Code''s requirements for client funds, kept separate and properly accounted for', 'They may be mixed freely with the FSP''s own funds', 'They need not be recorded', 'B', 'Client money and premiums must be dealt with strictly per the Code — separated, safeguarded and accounted for — not used as the FSP''s own resources.', 'GCC BN80 of 2003, s10'),
(56, 'general_code_of_conduct', 4, 'Consider: i. Providers must avoid and disclose conflicts of interest. ii. Disclosures must be made in plain language. iii. A provider may give advice without any regard to the client''s circumstances. iv. Records of advice must be retained. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv reflect Code duties. Statement iii is wrong — advice must be appropriate to the client''s needs and circumstances following a suitability analysis.', 'GCC BN80 of 2003'),
(57, 'general_code_of_conduct', 4, 'Consider the conflict-of-interest provisions: i. An FSP must adopt and maintain a conflict of interest management policy. ii. Conflicts must be disclosed to clients. iii. Immaterial financial interests below a prescribed threshold may be received. iv. A provider may keep conflicts secret if disclosure is inconvenient. Which combination is CORRECT?', 'i, ii and iii only', 'i and iv only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iii are correct. Statement iv is wrong — conflicts must be avoided where possible and otherwise disclosed, never concealed.', 'GCC BN80 of 2003, s3A'),

-- ======================= NEEDS ANALYSIS =======================
(58, 'needs_analysis', 1, 'A needs analysis required before furnishing advice is mandated by which section of the General Code?', 'Section 4', 'Section 8', 'Section 14', 'Section 17', 'B', 'Section 8 of the General Code requires a suitability (needs) analysis before advice is given.', 'GCC BN80 of 2003, s8'),
(59, 'needs_analysis', 2, 'What must a proper needs analysis take into account?', 'Only the product the FSP most wants to sell', 'The client''s financial situation, needs, objectives and risk profile, and relevant existing products', 'Only the client''s age', 'Nothing; advice can be generic', 'B', 'A needs analysis must consider the client''s circumstances — financial situation, objectives, risk profile and existing products — to ensure suitability.', 'GCC BN80 of 2003, s8'),
(60, 'needs_analysis', 2, 'After conducting a needs analysis, the advisor must ensure the recommended product is:', 'The one with the highest commission', 'Appropriate to the client''s identified needs and circumstances', 'Always the cheapest available', 'Chosen at random', 'B', 'Suitability means the recommended product must appropriately match the client''s identified needs and circumstances.', 'GCC BN80 of 2003, s8'),
(61, 'needs_analysis', 2, 'Why must the basis of the needs analysis and resulting advice be recorded?', 'It is not required to be recorded', 'To evidence that suitable advice was given and to support the record of advice', 'Only for tax purposes', 'Only if the client complains', 'B', 'Recording the analysis and advice demonstrates that the advice was suitable and forms part of the mandatory record of advice.', 'GCC BN80 of 2003, ss8-9'),
(62, 'needs_analysis', 3, 'A client refuses to disclose key financial information needed for a full needs analysis. What must the advisor do?', 'Proceed and guarantee the advice is suitable', 'Inform the client of the limitations and risks of advice based on incomplete information and record this', 'Refuse to ever deal with the client again', 'Complete the analysis using fabricated figures', 'B', 'Where information is incomplete because the client withholds it, the advisor must alert the client to the limitations and risks and document that the advice rests on a restricted basis.', 'GCC BN80 of 2003, s8(1)(a)'),
(63, 'needs_analysis', 3, 'A client urgently wants cover and a full analysis is not possible. What is the correct approach?', 'Decline to assist entirely', 'Disclose the limited scope, explain the risks, and advise the client to consider whether the product is appropriate', 'Provide advice and claim a full analysis was done', 'Sell the most expensive product available', 'B', 'When a complete analysis is not feasible, the advisor must disclose the limited basis, highlight the risks, and let the client decide on suitability.', 'GCC BN80 of 2003, s8'),
(64, 'needs_analysis', 3, 'In a replacement scenario, what additional needs-analysis step is required?', 'No additional step is needed', 'A comparison of the features, costs and risks of the existing product against the proposed product', 'Only the new product''s benefits need be shown', 'The client must cancel the old product first without comparison', 'B', 'A replacement requires a comparison of the existing and proposed products so the client understands the implications before switching.', 'GCC BN80 of 2003, s8'),
(65, 'needs_analysis', 4, 'Consider: i. A needs analysis must precede advice. ii. The analysis must consider existing products held by the client. iii. The client''s risk profile is irrelevant to suitability. iv. The advisor must record the basis of the advice. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — the client''s risk profile is central to assessing suitability.', 'GCC BN80 of 2003, ss8-9'),
(66, 'needs_analysis', 4, 'Consider: i. Suitable advice may ignore the client''s budget. ii. The advisor must identify the client''s objectives. iii. Incomplete information must be flagged to the client. iv. The advice must be appropriate to the client''s circumstances. Which combination is CORRECT?', 'ii, iii and iv only', 'i and ii only', 'i, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements ii, iii and iv are correct. Statement i is wrong — affordability and the client''s financial situation are integral to suitable advice.', 'GCC BN80 of 2003, s8'),
(67, 'needs_analysis', 2, 'Which of the following best describes the consequence of giving advice without a needs analysis?', 'There is no consequence', 'The advice may be unsuitable, exposing the FSP to complaints, Ombud determinations and regulatory sanction', 'The client is automatically barred from complaining', 'The product supplier becomes liable instead of the FSP', 'B', 'Omitting the needs analysis risks unsuitable advice and exposes the FSP to Ombud complaints and regulatory action.', 'GCC BN80 of 2003, s8'),

-- ======================= DISCLOSURE REQUIREMENTS =======================
(68, 'disclosure_requirements', 1, 'Disclosure of information about the product supplier is dealt with under which section of the General Code?', 'Section 4', 'Section 8', 'Section 12', 'Section 17', 'A', 'Section 4 of the General Code governs disclosures concerning the product supplier.', 'GCC BN80 of 2003, s4'),
(69, 'disclosure_requirements', 2, 'Which of the following must a provider disclose about itself to a client?', 'Only its telephone number', 'Its name, physical address, and the categories of financial services it is licensed to render', 'Nothing, unless asked', 'Only its commission rate', 'B', 'A provider must disclose identifying particulars including name, address and the categories/subcategories for which it is authorised.', 'GCC BN80 of 2003, s5'),
(70, 'disclosure_requirements', 2, 'When must disclosures generally be made to a client?', 'After the product has lapsed', 'At the earliest reasonable opportunity, and in any event before or at the time of rendering the service', 'Only at claim stage', 'Only in the following tax year', 'B', 'Disclosures must be made timeously — at the earliest reasonable opportunity — so the client can make an informed decision before concluding the transaction.', 'GCC BN80 of 2003, ss4-7'),
(71, 'disclosure_requirements', 2, 'In what manner must disclosures be made under the General Code?', 'In technical jargon to appear professional', 'In plain language, adequate and appropriate, avoiding uncertainty or confusion', 'Only verbally and never confirmed', 'Only in a language the client does not understand', 'B', 'Disclosures must be in plain language, factually correct, adequate and appropriate so the client can understand them.', 'GCC BN80 of 2003, s3'),
(72, 'disclosure_requirements', 2, 'What must be disclosed to a client regarding the provider''s remuneration?', 'Nothing; remuneration is confidential', 'The nature and, where reasonable, the extent of fees, commission or other remuneration the provider will receive', 'Only the product supplier''s profit', 'Only at the client''s written request after five years', 'B', 'The client must be informed about the fees, commission or incentives the provider will earn, so any conflicts are transparent.', 'GCC BN80 of 2003, ss4-7'),
(73, 'disclosure_requirements', 3, 'A provider gives detailed verbal disclosures during a meeting. What further step does the Code require?', 'No further step; verbal disclosure is always sufficient', 'Confirm the disclosures to the client in writing (or another appropriate recordable form) within a reasonable time', 'Have the client sign a blank form', 'Send the disclosures only to the product supplier', 'B', 'Verbal disclosures must be confirmed in writing or another recordable format within a reasonable time so the client has a durable record.', 'GCC BN80 of 2003, s7'),
(74, 'disclosure_requirements', 3, 'During a sale, the advisor realises they have an ownership interest in the recommended product supplier. What must they do?', 'Hide the interest to avoid losing the sale', 'Disclose the conflict of interest to the client and manage it per the conflict of interest policy', 'Cancel the client''s existing products', 'Refer the client to the FAIS Ombud', 'B', 'Any conflict of interest, including an ownership link to the product supplier, must be disclosed to the client and managed under the FSP''s conflict policy.', 'GCC BN80 of 2003, ss3A, 4'),
(75, 'disclosure_requirements', 3, 'A client asks whether the projected investment returns shown are guaranteed. What disclosure principle applies?', 'Promise the returns to secure the sale', 'Clearly disclose that projected/illustrative values are not guaranteed and explain the associated risks', 'Refuse to answer', 'State that all investments are risk-free', 'B', 'The provider must not create false expectations; non-guaranteed projections and the related risks must be clearly disclosed.', 'GCC BN80 of 2003, s7'),
(76, 'disclosure_requirements', 4, 'Consider: i. Charges and fees must be disclosed. ii. Disclosures must be in plain language. iii. Material conflicts of interest must be disclosed. iv. Disclosures may be deferred until after the client has signed. Which combination is CORRECT?', 'i, ii and iii only', 'i and iv only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iii are correct. Statement iv is wrong — disclosures must be made before or at the time of rendering the service, not deferred until after signing.', 'GCC BN80 of 2003, ss3-7'),
(77, 'disclosure_requirements', 1, 'True or false: monetary obligations the client will incur, such as premiums and charges, must be disclosed before concluding a transaction.', 'False — only at claim stage', 'True — the client''s monetary obligations must be disclosed beforehand', 'False — only the product supplier needs to know', 'True — but only for investments over R1 million', 'B', 'The client''s monetary obligations and the nature of charges must be disclosed up front so the client understands the cost.', 'GCC BN80 of 2003, s7'),

-- ======================= FSCA LICENSING =======================
(78, 'fsca_licensing', 1, 'Which authority issues licences to Financial Services Providers under the FAIS Act?', 'The FAIS Ombud', 'The Financial Sector Conduct Authority (FSCA)', 'The Prudential Authority', 'The Council for Medical Schemes', 'B', 'The FSCA is the market-conduct regulator that authorises and licenses FSPs under the FAIS Act.', 'FAIS Act s8; FSR Act'),
(79, 'fsca_licensing', 2, 'Which FSP category authorises a provider to manage investments on a discretionary basis for clients?', 'Category I', 'Category II', 'Category III', 'Category IV', 'B', 'Category II authorises discretionary financial services (managing client investments under a discretionary mandate). Category I covers advice and intermediary services.', 'FAIS Act; FSCA licensing categories'),
(80, 'fsca_licensing', 2, 'Which category typically applies to an FSP that only renders advice and intermediary services without discretionary or administrative mandates?', 'Category I', 'Category II', 'Category IIA', 'Category III', 'A', 'Category I FSPs render advice and/or intermediary services but do not exercise discretion over client investments or provide administrative services.', 'FAIS Act; FSCA licensing categories'),
(81, 'fsca_licensing', 2, 'What must an applicant for an FSP licence demonstrate?', 'Only a registered company name', 'Fit-and-proper Key Individuals, operational ability, financial soundness and adequate compliance arrangements', 'A minimum of 100 employees', 'Membership of a medical scheme', 'B', 'Licensing requires evidence of fit-and-proper KIs, operational ability, financial soundness and appropriate compliance arrangements.', 'FAIS Act s8; Board Notice 194 of 2017'),
(82, 'fsca_licensing', 2, 'Within how many days must an FSP notify the FSCA of a material change to information provided in its licence application?', '5 days', '15 days', '90 days', 'No notification is required', 'B', 'Material changes affecting the licence or the FSP''s fit-and-proper status must be reported to the FSCA promptly, generally within 15 days.', 'FAIS Act; General requirements'),
(83, 'fsca_licensing', 3, 'A business begins rendering financial advice for reward before its FSP licence is granted. What is the legal position?', 'This is permitted while the application is pending', 'It is an offence to render financial services without authorisation under the FAIS Act', 'It is allowed if the client consents', 'It is allowed for amounts under R10,000', 'B', 'Rendering financial services without the required FSP authorisation is a contravention of the FAIS Act and an offence.', 'FAIS Act s7'),
(84, 'fsca_licensing', 3, 'An existing Category I FSP wishes to begin offering a new product subcategory. What must it do?', 'Nothing; licences cover all products automatically', 'Apply to the FSCA to amend its licence to include the additional subcategory and ensure KIs/reps are competent for it', 'Simply start selling the new product', 'Surrender its current licence and reapply from scratch', 'B', 'Adding a product subcategory requires a licence amendment and proof that KIs and representatives are competent for the new line.', 'FAIS Act s8; Board Notice 194 of 2017'),
(85, 'fsca_licensing', 3, 'The FSCA grants a licence subject to specific conditions. What is the FSP''s obligation?', 'Conditions are merely advisory', 'The FSP must comply with the licence conditions; breach can lead to suspension or withdrawal', 'Conditions fall away after one year automatically', 'Only the KI must read the conditions', 'B', 'Licence conditions are binding; failure to comply exposes the FSP to suspension or withdrawal of its licence.', 'FAIS Act ss8, 9'),
(86, 'fsca_licensing', 1, 'What must a licensed FSP do with its licence/authorisation details?', 'Keep them secret from clients', 'Make its authorisation status available to clients (e.g. on disclosures and at its premises)', 'Share them only with the product supplier', 'Display them only during audits', 'B', 'An FSP must make its authorisation status transparent to clients as part of mandatory disclosure of its particulars.', 'GCC BN80 of 2003, s5'),
(87, 'fsca_licensing', 4, 'Consider: i. The FSCA issues FSP licences. ii. Licences specify the categories and subcategories of financial services. iii. An FSP may render any service regardless of its category. iv. Material changes must be reported to the FSCA. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — an FSP may only render services within its licensed categories and subcategories.', 'FAIS Act s8'),

-- ======================= LICENCE LAPSE & SUSPENSION =======================
(88, 'license_lapse_suspension', 1, 'Under section 11 of the FAIS Act, a licence lapses on the occurrence of which type of event?', 'A minor administrative error', 'Events such as voluntary cessation of business, liquidation, sequestration or death of a sole proprietor', 'A single client complaint', 'A change of office address', 'B', 'Section 11 provides for automatic lapsing of a licence upon defined events like liquidation, sequestration, cessation of business or death of a sole proprietor.', 'FAIS Act s11'),
(89, 'license_lapse_suspension', 2, 'What is the key distinction between suspension under section 9 and lapsing under section 11?', 'There is no distinction', 'Suspension is a regulatory action by the FSCA for non-compliance, whereas lapsing occurs automatically on defined events', 'Lapsing is a penalty and suspension is automatic', 'Both require a court order', 'B', 'Suspension/withdrawal under section 9 is a deliberate regulatory response to non-compliance; lapsing under section 11 happens automatically by operation of law.', 'FAIS Act ss9, 11'),
(90, 'license_lapse_suspension', 2, 'On what grounds may the FSCA suspend or withdraw an FSP''s licence under section 9?', 'The FSP earns high profits', 'The FSP no longer meets fit-and-proper requirements or has materially contravened the Act', 'The FSP changed its logo', 'The FSP hired new staff', 'B', 'Section 9 allows suspension or withdrawal where the FSP ceases to be fit and proper or materially contravenes the FAIS Act or its conditions.', 'FAIS Act s9'),
(91, 'license_lapse_suspension', 2, 'Before withdrawing an FSP''s licence, what must the FSCA generally afford the FSP?', 'Nothing; withdrawal is immediate and final', 'A fair procedure, including notice and an opportunity to make representations', 'A cash settlement', 'Automatic reinstatement', 'B', 'Administrative justice requires the FSCA to follow a fair procedure — notice and an opportunity to be heard — before withdrawing a licence.', 'FAIS Act s9; PAJA 2000'),
(92, 'license_lapse_suspension', 3, 'The FSCA suspends an FSP''s licence. What is the immediate effect on the FSP''s dealings with clients?', 'No effect; business continues as usual', 'The FSP may not render new financial services during suspension and must protect existing clients'' interests', 'The FSP must immediately liquidate', 'Clients automatically lose their cover', 'B', 'During suspension the FSP cannot render new financial services, and must take steps to protect existing clients while the suspension is in force.', 'FAIS Act s9'),
(93, 'license_lapse_suspension', 3, 'A suspended FSP remedies the compliance failures that led to the suspension. What can it seek?', 'Automatic permanent withdrawal', 'Reinstatement/lifting of the suspension by the FSCA once it is satisfied the issues are resolved', 'A refund of all levies ever paid', 'Conversion to a Category IV licence', 'B', 'Where the underlying non-compliance is remedied, the FSCA may lift the suspension and reinstate the licence subject to its satisfaction.', 'FAIS Act s9'),
(94, 'license_lapse_suspension', 3, 'A sole-proprietor FSP dies. What happens to the FSP licence?', 'It transfers automatically to the heirs', 'The licence lapses, as it was personal to the sole proprietor', 'It is suspended for 12 months then reinstated', 'It is sold with the estate', 'B', 'A licence held by a sole proprietor lapses on the proprietor''s death; it cannot simply be inherited or transferred.', 'FAIS Act s11'),
(95, 'license_lapse_suspension', 2, 'Which statement about a withdrawn licence is correct?', 'The FSP may keep rendering services informally', 'Once withdrawn, the FSP is no longer authorised and may not render financial services', 'Withdrawal only affects future clients', 'Withdrawal is the same as a warning', 'B', 'A withdrawn licence ends the FSP''s authorisation; rendering services thereafter is unlawful.', 'FAIS Act s9'),
(96, 'license_lapse_suspension', 4, 'Consider: i. Section 9 deals with suspension/withdrawal for non-compliance. ii. Section 11 deals with automatic lapsing. iii. Suspension and withdrawal require no fair procedure. iv. A lapsed or withdrawn FSP may not render financial services. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — suspension/withdrawal must follow a fair administrative procedure.', 'FAIS Act ss9, 11; PAJA 2000'),

-- ======================= BUSINESS RESCUE =======================
(97, 'business_rescue', 1, 'Business rescue proceedings for companies are primarily governed by which legislation?', 'The FAIS Act only', 'The Companies Act, 2008 (Chapter 6), read with FAIS provisions for FSPs', 'The Medical Schemes Act', 'The Labour Relations Act', 'B', 'Business rescue is a Companies Act, 2008 mechanism; for FSPs it operates together with the relevant FAIS provisions protecting clients.', 'Companies Act 2008, Ch 6; FAIS Act ss38A-38B'),
(98, 'business_rescue', 2, 'What is the primary objective of business rescue?', 'To liquidate the company as fast as possible', 'To facilitate the rehabilitation of a financially distressed company so it can continue on a solvent basis or yield a better return than liquidation', 'To debar all representatives', 'To increase shareholder bonuses', 'B', 'Business rescue aims to rehabilitate a financially distressed company, or to achieve a better outcome for creditors than immediate liquidation.', 'Companies Act 2008, s128'),
(99, 'business_rescue', 2, 'Who takes temporary management control of a company placed under business rescue?', 'The FAIS Ombud', 'A business rescue practitioner', 'The FSCA directly', 'The company''s clients', 'B', 'A business rescue practitioner is appointed to take temporary supervision and management of the company during rescue proceedings.', 'Companies Act 2008, ss128, 140'),
(100, 'business_rescue', 2, 'When an FSP enters business rescue, what is a key FAIS-related concern?', 'Maximising new sales', 'Protecting clients'' interests and any client funds or products held', 'Increasing the KI''s salary', 'Cancelling the compliance function', 'B', 'During financial distress the FSP must continue to protect client interests and safeguard client funds/products, consistent with FAIS obligations.', 'FAIS Act ss38A-38B'),
(101, 'business_rescue', 3, 'An FSP in financial distress is placed under business rescue. What should it do regarding the FSCA?', 'Nothing; the FSCA need not be told', 'Notify the FSCA and cooperate, given the impact on its licence status and clients', 'Immediately surrender all client records to creditors', 'Transfer its licence to the practitioner personally', 'B', 'Entering business rescue is a material event affecting the FSP''s status; the FSCA should be informed and the FSP must cooperate to protect clients.', 'FAIS Act ss38A-38B'),
(102, 'business_rescue', 3, 'How does the insolvency of a natural-person sole proprietor FSP differ from company business rescue?', 'There is no difference', 'A natural person is subject to sequestration under insolvency law, whereas business rescue applies to companies', 'Sole proprietors use business rescue and companies use sequestration', 'Both are handled by the FAIS Ombud', 'B', 'Sequestration applies to the insolvent estate of a natural person; business rescue is a corporate remedy for companies in financial distress.', 'Insolvency Act; Companies Act 2008'),
(103, 'business_rescue', 4, 'Consider: i. Business rescue seeks to rehabilitate a distressed company. ii. A practitioner supervises the company during rescue. iii. An FSP in distress may disregard client-protection duties. iv. Sequestration applies to natural persons. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — client-protection duties continue during financial distress.', 'Companies Act 2008; FAIS Act ss38A-38B'),
(104, 'business_rescue', 4, 'Consider: i. Liquidation results in the winding-up of the company. ii. Business rescue is an alternative aimed at recovery. iii. Client interests rank as irrelevant during winding-up of an FSP. iv. The FSCA has an interest in how a distressed FSP treats clients. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — protecting client interests remains important even during winding-up of an FSP.', 'Companies Act 2008; FAIS Act ss38A-38B'),

-- ======================= FICA & AML =======================
(105, 'fica_aml', 1, 'Which body is established by FICA to receive and analyse financial intelligence?', 'The FSCA', 'The Financial Intelligence Centre (FIC)', 'The FAIS Ombud', 'The Prudential Authority', 'B', 'FICA establishes the Financial Intelligence Centre (FIC) to collect, analyse and disseminate financial intelligence to combat money laundering and terror financing.', 'FICA Act 38 of 2001'),
(106, 'fica_aml', 2, 'What core obligation does FICA impose on accountable institutions when establishing a business relationship?', 'To ignore client identity', 'To conduct customer due diligence (know-your-customer), including identifying and verifying the client', 'To report all clients to SARS', 'To guarantee investment returns', 'B', 'Accountable institutions must perform customer due diligence — identifying and verifying clients (and beneficial owners) — before or during onboarding.', 'FICA Act 38 of 2001'),
(107, 'fica_aml', 2, 'For how long must an accountable institution retain records relating to client identity and transactions under FICA?', '1 year', '3 years', 'At least 5 years', '6 months', 'C', 'FICA requires that identity and transaction records be retained for at least 5 years (generally from termination of the relationship or conclusion of the transaction).', 'FICA Act 38 of 2001'),
(108, 'fica_aml', 2, 'What document must an accountable institution develop and maintain under FICA to manage money-laundering risk?', 'A marketing plan', 'A Risk Management and Compliance Programme (RMCP)', 'A medical scheme rulebook', 'A discretionary mandate', 'B', 'FICA requires accountable institutions to develop, document and maintain a Risk Management and Compliance Programme (RMCP) tailored to their ML/TF risks.', 'FICA Act 38 of 2001, s42'),
(109, 'fica_aml', 2, 'What heightened measure does FICA require for a politically exposed person (PEP) or prominent influential person?', 'No special treatment', 'Enhanced due diligence, including senior management approval and source-of-funds scrutiny', 'Automatic refusal of all business', 'A reduced record-keeping period', 'B', 'PEPs/prominent influential persons attract enhanced due diligence — including senior approval and establishing source of funds/wealth — due to higher corruption and laundering risk.', 'FICA Act 38 of 2001'),
(110, 'fica_aml', 3, 'A representative notices a transaction that appears designed to disguise the proceeds of crime. What must be done?', 'Ignore it to protect the client relationship', 'Report the suspicious or unusual transaction to the FIC within the prescribed period', 'Tell the client they are suspected', 'Refund the client and close the file quietly', 'B', 'Suspicious and unusual transactions must be reported to the FIC within the prescribed period; tipping off the client is itself an offence.', 'FICA Act 38 of 2001, s29'),
(111, 'fica_aml', 3, 'A client wishes to deposit a large cash amount above the prescribed threshold. What FICA obligation may arise?', 'None; cash is exempt', 'A cash threshold report to the FIC for cash transactions above the prescribed limit', 'Automatic debarment of the client', 'A levy payable to the FSCA', 'B', 'Cash transactions above the prescribed threshold trigger a cash threshold report to the FIC.', 'FICA Act 38 of 2001, s28'),
(112, 'fica_aml', 3, 'An FSP has no AML training programme and staff cannot identify red flags. What is the FICA concern?', 'There is no concern', 'The FSP fails its duty to train staff and implement its RMCP, exposing it to administrative sanctions', 'Only the FAIS Ombud is affected', 'Training is required only for directors', 'B', 'FICA requires ongoing staff training and implementation of the RMCP; failing to do so is a compliance breach attracting administrative sanctions.', 'FICA Act 38 of 2001, s43'),
(113, 'fica_aml', 1, 'What is the stated primary objective of FICA?', 'To license financial advisors', 'To combat money laundering and the financing of terrorism', 'To regulate medical schemes', 'To set FSP commission rates', 'B', 'FICA''s primary purpose is to combat money laundering and terrorist financing through a regulatory and reporting framework.', 'FICA Act 38 of 2001'),
(114, 'fica_aml', 4, 'Consider: i. Accountable institutions must conduct customer due diligence. ii. Suspicious transactions must be reported to the FIC. iii. Records may be destroyed immediately after onboarding. iv. An RMCP must be maintained. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — records must be retained for at least 5 years, not destroyed after onboarding.', 'FICA Act 38 of 2001'),

-- ======================= REGULATORY LEVIES =======================
(115, 'regulatory_levies', 1, 'To whom must an FSP pay its annual regulatory levies?', 'The FAIS Ombud only', 'The financial sector regulator(s) as prescribed (collected for the FSCA and related bodies)', 'The product supplier', 'The client', 'B', 'Annual levies are payable to the prescribed financial sector regulator(s) and fund the regulatory and ombud systems.', 'Financial Services Board Act s15A; GN362 of 2018'),
(116, 'regulatory_levies', 2, 'What is the primary purpose of regulatory levies imposed on FSPs?', 'To pay client claims', 'To fund the operations of the financial sector regulators and related statutory bodies', 'To increase product supplier profits', 'To pay representatives'' salaries', 'B', 'Levies provide the funding base for the regulators and statutory bodies that supervise the financial sector.', 'Financial Services Board Act s15A'),
(117, 'regulatory_levies', 2, 'How are the amounts of annual levies typically determined?', 'They are fixed permanently and never change', 'They are prescribed and updated periodically by published notice', 'They are set by each FSP itself', 'They are decided by the FAIS Ombud', 'B', 'Levy amounts are prescribed and updated from time to time by published government/board notice.', 'Financial Services Board Act s15A; GN362 of 2018'),
(118, 'regulatory_levies', 2, 'What is the difference between a once-off application fee and an annual levy?', 'They are identical', 'An application fee is paid when applying for authorisation, while a levy is a recurring annual charge to fund regulation', 'A levy is paid only once', 'An application fee recurs every month', 'B', 'Application fees are paid at the authorisation stage; levies are recurring annual charges supporting ongoing regulation.', 'FAIS Act; Financial Services Board Act s15A'),
(119, 'regulatory_levies', 3, 'An FSP fails to pay its annual levy by the due date. What is a likely consequence?', 'Nothing happens', 'Penalties and/or interest may be imposed, and persistent non-payment can affect the FSP''s standing with the regulator', 'The FSP is automatically debarred', 'The client must pay the levy instead', 'B', 'Late or non-payment of levies can attract penalties and interest and may affect the FSP''s regulatory standing.', 'Financial Services Board Act s15A; levy notices'),
(120, 'regulatory_levies', 3, 'A newly authorised FSP is licensed part-way through the levy year. How is its levy typically treated?', 'It pays a full year regardless', 'It may be calculated on a pro-rata basis for the portion of the period it is licensed, as prescribed', 'It pays no levy ever', 'It pays the next FSP''s levy', 'B', 'Levies for an FSP authorised during a levy period are commonly calculated on a pro-rata basis as set out in the applicable notice.', 'Financial Services Board Act s15A; levy notices'),
(121, 'regulatory_levies', 4, 'Consider: i. Levies fund the regulators. ii. Levy amounts are prescribed by notice. iii. FSPs may unilaterally decide not to pay levies without consequence. iv. Late payment may attract penalties. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — levies are compulsory and non-payment has consequences.', 'Financial Services Board Act s15A'),
(122, 'regulatory_levies', 4, 'Consider: i. Levies are recurring annual charges. ii. Application fees are once-off. iii. Levies are voluntary donations. iv. Levy notices are published periodically. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — levies are compulsory statutory charges, not voluntary donations.', 'Financial Services Board Act s15A'),

-- ======================= DOFA TIMELINES =======================
(123, 'dofa_timelines', 1, 'What does the abbreviation DOFA stand for?', 'Date of Financial Audit', 'Date of First Appointment', 'Declaration of Financial Affairs', 'Duty of Fair Advice', 'B', 'DOFA is the Date of First Appointment — the date a person is first appointed as a representative, from which competency timelines run.', 'Board Notice 194 of 2017'),
(124, 'dofa_timelines', 2, 'Within how long of DOFA must a representative pass the relevant regulatory examination (e.g. RE5)?', '6 months', '2 years', '6 years', '10 years', 'B', 'A representative must pass the applicable regulatory examination within 2 years of their DOFA.', 'Board Notice 194 of 2017'),
(125, 'dofa_timelines', 2, 'Within how long of DOFA must a representative obtain a full recognised qualification?', '2 years', '4 years', '6 years', 'No deadline applies', 'C', 'A representative must obtain a full recognised qualification appropriate to their category within 6 years of DOFA.', 'Board Notice 194 of 2017'),
(126, 'dofa_timelines', 2, 'Over what period is continuous professional development (CPD) measured?', 'A calendar year, 1 January to 31 December', 'A 12-month CPD cycle running 1 June to 31 May', 'A 3-year cycle', 'There is no fixed cycle', 'B', 'CPD is measured over a 12-month cycle that runs from 1 June to 31 May.', 'Board Notice 194 of 2017'),
(127, 'dofa_timelines', 3, 'A representative is appointed and immediately begins advising on a new product. What training requirement applies before they may render services on that product?', 'None; training is optional', 'Product-specific training relevant to that product must be completed before rendering services on it', 'They have 6 years to do product training', 'Only the KI needs product training', 'B', 'Product-specific training relevant to a product must be completed before a representative renders financial services in respect of that product.', 'Board Notice 194 of 2017'),
(128, 'dofa_timelines', 3, 'A representative moves from one FSP to another. How is their DOFA affected for competency-timeline purposes?', 'A new DOFA always starts at zero', 'Their original DOFA for the relevant category generally carries over; timelines are not reset simply by changing employer', 'DOFA is abolished on resignation', 'The new FSP sets any date it likes', 'B', 'Competency timelines run from the person''s first appointment in the relevant category; moving FSPs does not simply reset the clock.', 'Board Notice 194 of 2017'),
(129, 'dofa_timelines', 4, 'Consider: i. RE5 must be passed within 2 years of DOFA. ii. A full qualification must be obtained within 6 years of DOFA. iii. Class-of-business training may be ignored. iv. CPD runs on a 1 June to 31 May cycle. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — class-of-business training is a mandatory competency requirement, not optional.', 'Board Notice 194 of 2017'),
(130, 'dofa_timelines', 4, 'Consider: i. Class-of-business training must precede rendering services in that class. ii. Product-specific training is required for specific products. iii. CPD obligations end once a qualification is obtained. iv. Competency timelines run from DOFA. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — CPD is an ongoing annual obligation that continues after qualification.', 'Board Notice 194 of 2017'),

-- ======================= REPRESENTATIVE OVERSIGHT =======================
(131, 'representative_oversight', 1, 'What record must every FSP maintain in respect of the persons who act for it?', 'A register of clients only', 'An up-to-date register of representatives (and key individuals)', 'A register of competitors', 'No register is required', 'B', 'An FSP must keep an up-to-date register of its representatives and key individuals, reflecting their status and the services they may render.', 'FAIS Act s13'),
(132, 'representative_oversight', 2, 'A representative who has not yet met the competency requirements may render financial services only:', 'Independently, with no oversight', 'Under supervision, in accordance with the supervision requirements', 'After being debarred', 'Once they reach age 30', 'B', 'A representative who has not met all competency requirements may act only under an appropriate supervision arrangement until they do.', 'Board Notice 194 of 2017; FAIS supervision requirements'),
(133, 'representative_oversight', 2, 'Within how many days must an FSP update the representative register and inform the FSCA of material changes?', '5 days', '15 days', '90 days', 'No obligation exists', 'B', 'Material changes to the representative register (appointments, terminations, debarments) must be updated and reported to the FSCA within the prescribed period (generally 15 days).', 'FAIS Act s13'),
(134, 'representative_oversight', 2, 'Who is primarily accountable for managing and overseeing the conduct of an FSP''s representatives?', 'The client', 'The Key Individual responsible for the relevant financial services', 'The FAIS Ombud', 'The product supplier', 'B', 'The relevant Key Individual is responsible for managing and overseeing the representatives rendering services in their area.', 'FAIS Act s8; Board Notice 194 of 2017'),
(135, 'representative_oversight', 3, 'A KI discovers a representative has missed the 2-year RE5 deadline. What is the correct immediate step?', 'Allow the rep to continue advising independently', 'Place the representative under supervision so they cannot render advice independently, and remedy the gap urgently', 'Debar the representative on the spot without process', 'Do nothing until the next FSCA audit', 'B', 'A rep who misses competency deadlines cannot act independently; the KI must impose a supervision arrangement and address the compliance gap promptly.', 'Board Notice 194 of 2017; FAIS Notice 86 of 2018'),
(136, 'representative_oversight', 3, 'A supervised representative wants to finalise advice and sign off independently. Is this permitted?', 'Yes, supervision is only nominal', 'No — a supervised representative cannot act independently; their advice must be overseen per the supervision arrangement', 'Yes, if the client agrees', 'Only on Fridays', 'B', 'Supervision means the representative''s services are monitored and the supervisor remains responsible; the rep cannot give independent sign-off until competent.', 'Board Notice 194 of 2017'),
(137, 'representative_oversight', 3, 'How should an FSP ensure ongoing fitness of its representatives?', 'Check competence only once at appointment', 'Monitor representatives on an ongoing basis, ensuring they remain fit and proper and meet CPD and competency obligations', 'Rely solely on the product supplier', 'Assess them only when a complaint arises', 'B', 'Fitness and propriety is a continuous requirement; the FSP must monitor representatives on an ongoing basis, including CPD and competency.', 'Board Notice 194 of 2017'),
(138, 'representative_oversight', 4, 'Consider: i. The FSP must maintain a representative register. ii. Representatives must remain fit and proper continuously. iii. A representative who fails competency timelines may continue unsupervised. iv. Debarments must be recorded and reported. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — such a representative must be supervised, not left to act unsupervised.', 'FAIS Act s13; Board Notice 194 of 2017'),
(139, 'representative_oversight', 4, 'Consider: i. The KI oversees representatives'' conduct. ii. Changes to the register must be reported to the FSCA. iii. Supervised reps may sign off advice independently. iv. Representatives must meet CPD obligations. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — supervised representatives cannot give independent sign-off.', 'FAIS Act ss8, 13; Board Notice 194 of 2017'),

-- ======================= FIT AND PROPER =======================
(140, 'fit_and_proper', 1, 'The fit-and-proper requirements for FSPs, KIs and representatives are primarily set out in which instrument?', 'Board Notice 80 of 2003', 'Board Notice 194 of 2017', 'FICA Act 38 of 2001', 'Government Notice 362 of 2018', 'B', 'The Determination of Fit and Proper Requirements is contained in Board Notice 194 of 2017.', 'Board Notice 194 of 2017'),
(141, 'fit_and_proper', 1, 'Which of the following is NOT one of the recognised fit-and-proper requirement areas?', 'Honesty, integrity and good standing', 'Competence', 'Financial soundness', 'Marketing budget size', 'D', 'The fit-and-proper areas are honesty/integrity/good standing, competence, operational ability, financial soundness and continuous professional development — marketing budget is not one of them.', 'Board Notice 194 of 2017'),
(142, 'fit_and_proper', 2, 'What does the competence requirement encompass?', 'Only a matric certificate', 'Qualifications, regulatory examinations, experience, class-of-business and product training, and CPD', 'Only years of age', 'Only a clear criminal record', 'B', 'Competence comprises minimum qualifications, regulatory exams, experience, class-of-business/product training and ongoing CPD.', 'Board Notice 194 of 2017'),
(143, 'fit_and_proper', 2, 'What does the financial soundness requirement generally mean for a representative or FSP?', 'They must be wealthy', 'They must not be insolvent (e.g. unrehabilitated insolvent) and must meet prescribed financial soundness criteria', 'They must own property', 'They must have no debt of any kind', 'B', 'Financial soundness focuses on matters such as not being an unrehabilitated insolvent and meeting prescribed solvency/working-capital criteria where applicable.', 'Board Notice 194 of 2017'),
(144, 'fit_and_proper', 2, 'How is the honesty and integrity requirement typically assessed?', 'By sales volume', 'By considering matters such as criminal convictions for dishonesty, prior debarments, and disciplinary findings', 'By the size of the office', 'By the number of clients', 'B', 'Honesty and integrity is assessed with reference to dishonesty-related convictions, prior debarments, disciplinary actions and similar conduct.', 'Board Notice 194 of 2017'),
(145, 'fit_and_proper', 3, 'A prospective representative has an unrehabilitated insolvency. Which fit-and-proper area is most directly engaged?', 'Operational ability', 'Financial soundness', 'CPD', 'Advertising', 'B', 'An unrehabilitated insolvency directly engages the financial soundness requirement.', 'Board Notice 194 of 2017'),
(146, 'fit_and_proper', 3, 'A start-up FSP cannot show adequate systems, processes or premises to render the services applied for. Which requirement is in issue?', 'Honesty and integrity', 'Operational ability', 'CPD', 'Levies', 'B', 'The capacity to deliver services — systems, processes, resources, premises and governance — falls under operational ability.', 'Board Notice 194 of 2017'),
(147, 'fit_and_proper', 3, 'A representative obtains a qualification that is not on the FSCA''s list of recognised qualifications. What is the position?', 'It automatically satisfies the competence requirement', 'It may not satisfy the qualification requirement, since the qualification must be recognised for the relevant category', 'Qualifications are irrelevant to competence', 'It satisfies the honesty requirement instead', 'B', 'Only qualifications recognised by the FSCA for the relevant category count toward the qualification component of competence.', 'Board Notice 194 of 2017'),
(148, 'fit_and_proper', 2, 'What does the "good standing" element of honesty and integrity consider?', 'The person''s social media following', 'Whether the person has been refused membership, debarred, or had authorisation withdrawn previously', 'The person''s height', 'The person''s marketing spend', 'B', 'Good standing considers prior refusals, debarments, withdrawals of authorisation and similar adverse regulatory history.', 'Board Notice 194 of 2017'),
(149, 'fit_and_proper', 4, 'Consider: i. Fit and proper includes honesty, competence, operational ability, financial soundness and CPD. ii. Fit and proper need only be met at appointment. iii. An unrehabilitated insolvent fails financial soundness. iv. Recognised qualifications support the competence requirement. Which combination is CORRECT?', 'i, iii and iv only', 'i and ii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, iii and iv are correct. Statement ii is wrong — fit and proper must be met continuously, not only at appointment.', 'Board Notice 194 of 2017'),
(150, 'fit_and_proper', 4, 'Consider: i. CPD is part of competence. ii. Operational ability concerns the capacity to deliver the services. iii. Dishonesty convictions are irrelevant to fitness. iv. Financial soundness includes not being an unrehabilitated insolvent. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — dishonesty-related convictions are highly relevant to honesty and integrity.', 'Board Notice 194 of 2017'),

-- ======================= MEDICAL SCHEMES ACT =======================
(151, 'medical_schemes_act', 1, 'The Medical Schemes Act is which numbered Act?', 'Act 37 of 2002', 'Act 131 of 1998', 'Act 38 of 2001', 'Act 9 of 2017', 'B', 'The Medical Schemes Act is Act 131 of 1998.', 'Medical Schemes Act 131 of 1998'),
(152, 'medical_schemes_act', 2, 'Which body regulates medical schemes in South Africa?', 'The FSCA', 'The Council for Medical Schemes (CMS)', 'The FAIS Ombud', 'The Prudential Authority', 'B', 'Medical schemes are regulated by the Council for Medical Schemes (CMS) under the Medical Schemes Act.', 'Medical Schemes Act 131 of 1998'),
(153, 'medical_schemes_act', 2, 'How do medical schemes differ fundamentally from typical insurers?', 'They are profit-maximising companies', 'They are not-for-profit entities operating for the benefit of their members', 'They are government departments', 'They are unregulated', 'B', 'Medical schemes are non-profit entities run for the benefit of members, distinguishing them from for-profit insurers.', 'Medical Schemes Act 131 of 1998'),
(154, 'medical_schemes_act', 2, 'What are Prescribed Minimum Benefits (PMBs)?', 'Optional extras members may decline', 'A defined set of minimum benefits all medical schemes must cover', 'A type of investment return', 'A levy payable to the FSCA', 'B', 'PMBs are a statutory minimum set of conditions and benefits that all registered medical schemes must cover.', 'Medical Schemes Act 131 of 1998; Regulations'),
(155, 'medical_schemes_act', 2, 'What is the difference between an open and a restricted medical scheme?', 'There is no difference', 'An open scheme admits any member of the public, whereas a restricted scheme limits membership (e.g. to an employer or profession)', 'Open schemes are unregulated', 'Restricted schemes pay no claims', 'B', 'Open schemes are available to the general public; restricted schemes limit eligibility to defined groups such as employees of a particular employer.', 'Medical Schemes Act 131 of 1998'),
(156, 'medical_schemes_act', 3, 'An advisor wishes to advise clients on medical scheme membership. What accreditation is required?', 'None; FAIS authorisation alone suffices', 'Accreditation as a broker under the Medical Schemes Act, in addition to applicable FAIS requirements', 'A medical degree', 'A Category II FSP licence', 'B', 'Advising on medical schemes requires broker accreditation under the Medical Schemes Act, over and above any applicable FAIS requirements.', 'Medical Schemes Act 131 of 1998'),
(157, 'medical_schemes_act', 3, 'A client confuses a health-insurance policy with a medical scheme. What is the key regulatory distinction the advisor should explain?', 'They are the same thing', 'Medical schemes are regulated under the Medical Schemes Act by the CMS, while certain health insurance products fall under insurance/FAIS regulation', 'Neither is regulated', 'Only medical schemes pay claims', 'B', 'Medical schemes fall under the Medical Schemes Act/CMS, whereas demarcated health-insurance products are regulated under insurance law and FAIS — the distinction affects benefits and protections.', 'Medical Schemes Act 131 of 1998; Demarcation Regulations'),
(158, 'medical_schemes_act', 1, 'Which principle requires medical schemes to charge contributions without discriminating on the basis of health status?', 'Risk-rating', 'Community rating / open enrolment principles', 'Underwriting by age only', 'Free choice of premium', 'B', 'Medical schemes operate on community rating and open enrolment principles, so contributions are not based on an individual member''s health status.', 'Medical Schemes Act 131 of 1998'),
(159, 'medical_schemes_act', 4, 'Consider: i. Medical schemes are regulated by the CMS. ii. Medical schemes are non-profit. iii. Advising on medical schemes needs no accreditation at all. iv. PMBs must be covered by all schemes. Which combination is CORRECT?', 'i, ii and iv only', 'i and iii only', 'ii, iii and iv only', 'i, ii, iii and iv', 'A', 'Statements i, ii and iv are correct. Statement iii is wrong — advising on medical schemes requires broker accreditation under the Medical Schemes Act.', 'Medical Schemes Act 131 of 1998'),
(160, 'medical_schemes_act', 2, 'Why is it important for a Key Individual to understand the Medical Schemes Act interface with FAIS?', 'It is irrelevant to FSPs', 'Because health-related products may straddle medical-scheme and insurance/FAIS regulation, affecting licensing, accreditation and client protection', 'Because medical schemes set FSP levies', 'Because the CMS issues FSP licences', 'B', 'KIs must understand how medical-scheme regulation interfaces with FAIS/insurance regulation to ensure correct licensing, accreditation and client protection for health-related products.', 'Medical Schemes Act 131 of 1998; FAIS Act');
